export const DEFAULT_SENTENCES = [
  "He sprinkled chili flakes over the pasta to add a gentle heat.",
  "The stew thickened slowly as the vegetables softened in the pot.",
  "A drizzle of honey balanced the bitterness of the dark chocolate.",
  "They grilled the salmon until the skin became perfectly crisp.",
  "The bakery filled with the smell of freshly baked cinnamon rolls.",
  "She kneaded the dough patiently until it became smooth and elastic.",
  "The chef reduced the wine sauce until it turned glossy and rich.",
  "A handful of crushed pistachios added a satisfying crunch to the dessert.",
  "The risotto became creamy as he gradually stirred in warm broth.",
  "Freshly grated ginger gave the soup a bright, warming flavor.",
  "A new firmware update improved the security features on the device.",
  "The development team implemented containerization to streamline deployments.",
  "He monitored CPU usage as the microservices processed incoming requests.",
  "The platform used edge computing to reduce response times.",
  "Developers refactored legacy code to improve overall maintainability.",
  "An outage in the server cluster triggered an automatic failover sequence.",
  "The UI team redesigned the dashboard for better accessibility.",
  "QA engineers documented several bugs after running automated tests overnight.",
  "A script optimized the data pipeline, reducing processing time significantly.",
  "The network administrator updated routing tables to improve packet flow.",
  "Bond yields rose steadily as investors sought safer assets.",
  "The central bank issued a statement that shifted market expectations.",
  "A sudden drop in commodity prices affected several global indexes.",
  "Hedge funds rebalanced their positions to hedge against volatility.",
  "Corporate earnings reports fueled speculation about long-term growth.",
  "Financial analysts built predictive models to estimate revenue trends.",
  "The credit market tightened as interest rates climbed.",
  "Real estate investors evaluated capital flows across different regions.",
  "The stock rallied after positive announcements from regulators.",
  "A rescue shelter posted photos of newly adoptable puppies.",
  "The cat stretched lazily across the back of the sofa.",
  "A rabbit nibbled on fresh greens inside its enclosure.",
  "She took her dog to obedience classes three times a week.",
  "The hamster stored tiny seeds in the corner of its cage.",
  "A pair of kittens wrestled energetically on the living room rug.",
  "The parakeet chirped loudly when it heard footsteps approaching.",
  "The guinea pig squeaked happily when given its favorite snack.",
  "A senior dog rested peacefully after a long walk through the park.",
  "The aquarium glowed softly as the fish swam in slow circles.",
  "Students practiced solving equations to prepare for the math competition.",
  "He organized his notes before beginning his study session.",
  "The tutor reviewed sample questions to help him understand the concept better.",
  "A classroom debate encouraged students to defend their ideas logically.",
  "She submitted her research project after weeks of careful preparation.",
  "The science lab buzzed with excitement during the experiment.",
  "They created flashcards to memorize important historical dates.",
  "The lecturer explained the topic using diagrams and real-world examples.",
  "A study group formed to help each other revise before finals.",
  "He tossed fresh herbs into the pan just before serving the dish.",
  "The broth simmered gently, filling the room with a savory aroma.",
  "A swirl of cream gave the soup a silky finish.",
  "They toasted the bread until golden and crisp on the edges.",
  "The chef decorated the cake with edible flowers and powdered sugar.",
  "A squeeze of lime brightened the grilled vegetables instantly.",
  "The curry’s spices deepened after hours of slow cooking.",
  "The tart crust crumbled perfectly with each bite.",
  "He monitored API logs to diagnose a sudden spike in errors.",
  "The machine learning pipeline retrained models on updated datasets.",
  "A new authentication protocol strengthened the system’s defenses.",
  "The helpdesk resolved connectivity issues affecting remote users.",
  "Real-time metrics displayed traffic surges across multiple services.",
  "A patch fixed memory leaks that had caused repeated crashes.",
  "The blockchain node synced new blocks after a network upgrade.",
  "The cloud instance autoscaled to handle additional workload.",
  "She updated access permissions to improve data security.",
  "Retail investors reacted quickly to shifting market sentiment.",
  "The treasury department reviewed liquidity ratios before the audit.",
  "Foreign exchange rates fluctuated throughout the trading session.",
  "A dividend announcement boosted investor confidence overnight.",
  "The commodities market responded sharply to new supply forecasts.",
  "Analysts compiled quarterly data to predict future performance.",
  "A pension fund diversified holdings to reduce long-term exposure.",
  "International markets opened lower following geopolitical tension.",
  "The puppy barked excitedly when the doorbell rang.",
  "A small bird perched on the window ledge observing the room.",
  "He brushed his cat’s fur until it shone smoothly.",
  "The ferret darted playfully through a series of tunnels.",
  "A turtle settled quietly on its warm basking rock.",
  "She trained her parrot to repeat simple phrases.",
  "Students rehearsed their presentations in the school auditorium.",
  "He drafted an essay outline before writing the first paragraph.",
  "The librarian recommended several books to support his research.",
  "A digital learning app helped kids practice reading comprehension.",
];
